# Series

In [2]:
import numpy as np
import pandas as pd

In [3]:
from pandas import Series, DataFrame

In [3]:
pwd

'/content'

In [4]:
%pushd /content
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 10
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

/content

In [5]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
type(obj)

pandas.core.series.Series

In [7]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [10]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2["a"]

-5

In [13]:
obj2["d"] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

-  funkcja `np.exp()` służy do obliczania wartości funkcji wykładniczej dla każdego elementu tablicy

In [17]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
"b" in obj2

True

In [19]:
"e" in obj2

False

In [20]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [23]:
print(type(obj3.to_dict()), type(obj3))

<class 'dict'> <class 'pandas.core.series.Series'>

In [24]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3
obj4
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
obj4.name = "population"
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [31]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [32]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

# DataFrame

In [34]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [38]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [39]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [40]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [41]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [42]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [43]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [44]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [45]:
frame2["debt"] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [46]:
frame2["debt"] = np.arange(6.)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [47]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [48]:
frame2["debt"] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [49]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [50]:
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [52]:
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [53]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [54]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [55]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [56]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [57]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [58]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [59]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [60]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [61]:
index[1:]

Index(['b', 'c'], dtype='object')

In [5]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [6]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [4]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2
obj2.index is labels

True

In [ ]:
frame3
frame3.columns
"Ohio" in frame3.columns
2003 in frame3.index

In [ ]:
#! ipython id=63bf8fa08ef54a05b3b099a61cc89743
pd.Index(["foo", "foo", "bar", "bar"])

In [ ]:
#! ipython id=328712376009457e8a7d83146296bccf
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

In [ ]:
#! ipython id=5980e55c4b1f4943a6bf013a1898544a
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

In [ ]:
#! ipython id=fbc0d3b6adc64be781a6d9cbb7132352
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3
obj3.reindex(np.arange(6), method="ffill")

In [ ]:
#! ipython id=3a2e62814cda43e6924c63d519d47591
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

In [ ]:
#! ipython id=899fe1bb88214dd4ab543c8242adf628
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

In [ ]:
#! ipython id=b9b8180a14764143adb17041231fdf08
frame.reindex(states, axis="columns")

In [ ]:
#! ipython id=6d8400ea97fd4bd8bf704f18835cada3
frame.loc[["a", "d", "c"], ["California", "Texas"]]

In [ ]:
#! ipython id=21e5021229c34d05ac9ec0dec36c506d
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj
new_obj = obj.drop("c")
new_obj
obj.drop(["d", "c"])

In [ ]:
#! ipython id=d6ee7bd35ad844b8b31a02cc2345e8dc
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

In [ ]:
#! ipython id=59357e8a21f64a9fabdd36f5643dbb4f
data.drop(index=["Colorado", "Ohio"])

In [ ]:
#! ipython id=d55b792ba8924524857e51d43b177489
data.drop(columns=["two"])

In [ ]:
#! ipython id=4645ed672f144c4fb368d30c774f906a
data.drop("two", axis=1)
data.drop(["two", "four"], axis="columns")

In [ ]:
#! ipython id=85f497478a9d4b5e97aa8012912d1d2f
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj
obj["b"]
obj[1]
obj[2:4]
obj[["b", "a", "d"]]
obj[[1, 3]]
obj[obj < 2]

In [ ]:
#! ipython id=655B753DAA154E1FB24039C26C83060B
obj.loc[["b", "a", "d"]]

In [ ]:
#! ipython id=FE6AE0EAF21741D8A054BEF2C9CC57C8
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj1
obj2
obj1[[0, 1, 2]]
obj2[[0, 1, 2]]

In [ ]:
#! ipython id=82C31C77659740BF9AF1B87B9A392659
obj1.iloc[[0, 1, 2]]
obj2.iloc[[0, 1, 2]]

In [ ]:
#! ipython id=faaaebe3b978418f88cde6c84b3f7025
obj2.loc["b":"c"]

In [ ]:
#! ipython id=b1ef8c6f13f24aec959f541900023322
obj2.loc["b":"c"] = 5
obj2

In [ ]:
#! ipython id=a8c96c31128a41658f14d2442c891713
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data
data["two"]
data[["three", "one"]]

In [ ]:
#! ipython id=dd77a40e483f4eb18dcbf506fbcc5d2a
data[:2]
data[data["three"] > 5]

In [ ]:
#! ipython id=9511846494a343e99600772bda5cc9e1
data < 5

In [ ]:
#! ipython id=c8be1582b25543df91106bb41cc5e7f1
data[data < 5] = 0
data

In [ ]:
#! ipython id=68f97d0a40964d4084df3e6c69c7750c
data
data.loc["Colorado"]

In [ ]:
#! ipython id=0f49b78471e0479b9fe9aed7b3de7c3d
data.loc[["Colorado", "New York"]]

In [ ]:
#! ipython id=5003cd2010a5468daf398166ef509b78
data.loc["Colorado", ["two", "three"]]

In [ ]:
#! ipython id=abea7d531ec64961b975355fad10ed23
data.iloc[2]
data.iloc[[2, 1]]
data.iloc[2, [3, 0, 1]]
data.iloc[[1, 2], [3, 0, 1]]

In [ ]:
#! ipython id=729735e3373e433a97a215dc545059b3
data.loc[:"Utah", "two"]
data.iloc[:, :3][data.three > 5]

In [ ]:
#! ipython id=f3d7c4a30f744a2f9a01745b8fae3472
data.loc[data.three >= 2]

In [ ]:
#! ipython allow_exceptions id=06fa3619ab814c8a805051d3dc07a14d
ser = pd.Series(np.arange(3.))
ser
ser[-1]

In [ ]:
#! ipython id=67e50e342e664361802d030ed79cb05d
ser

In [ ]:
#! ipython id=6b6026d6df544f24b4db09fb1c10e3bb
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])
ser2[-1]

In [ ]:
#! ipython allow_exceptions id=f519b83b2d0e4d1fae95a7b27069b69d
ser.iloc[-1]

In [ ]:
#! ipython id=ce162f7e552f402e88b968b48d1b4e8c
ser[:2]

In [ ]:
#! ipython id=b52f3eac12614d848a86489c34c763b3
data.loc[:, "one"] = 1
data
data.iloc[2] = 5
data
data.loc[data["four"] > 5] = 3
data

In [ ]:
#! ipython suppress id=a66680e4e4944ed080d63272cc49a0fc
data.loc[data.three == 5]["three"] = 6

In [ ]:
#! ipython id=596c80a9a2b04827a21d6bbc850ca254
data

In [ ]:
#! ipython id=5a0fe0249caf4832bbca24428ac384c2
data.loc[data.three == 5, "three"] = 6
data

In [ ]:
#! ipython id=8e1ec27bfff145398d40159c0274a17d
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1
s2

In [ ]:
#! ipython id=968ac5a22c6b4dc99def5fbbc7bc5dad
s1 + s2

In [ ]:
#! ipython id=67d3d91915da4a38a5c048a14be15dd2
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1
df2

In [ ]:
#! ipython id=901b4e8f9e6c4d089d62839f975084da
df1 + df2

In [ ]:
#! ipython id=df97a438f4a843d99c3368c57b80860c
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
df1
df2
df1 + df2

In [ ]:
#! ipython id=1edb825335d94eb9a4a80836a75e4329
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))
df2.loc[1, "b"] = np.nan
df1
df2

In [ ]:
#! ipython id=78588cf651234834908f8023f96f677f
df1 + df2

In [ ]:
#! ipython id=ae29de7160e54c1ca33fabdc91ad44ee
df1.add(df2, fill_value=0)

In [ ]:
#! ipython id=c37b4e0701a343aba7236622cb3ecee0
1 / df1
df1.rdiv(1)

In [ ]:
#! ipython id=c47367ccc10648e29bf8e1b9a0ce21b6
df1.reindex(columns=df2.columns, fill_value=0)

In [ ]:
#! ipython id=702c34a6688847919fa2fadc17946eb4
arr = np.arange(12.).reshape((3, 4))
arr
arr[0]
arr - arr[0]

In [ ]:
#! ipython id=77a1cd84b9334c3e8bc12e79ca7c37b7
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]
frame
series

In [ ]:
#! ipython id=defba2a16851407cbf7d19dc036cfb6d
frame - series

In [ ]:
#! ipython id=949f3f67d1ac48d3a0e32eb51611e649
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2
frame + series2

In [ ]:
#! ipython id=29ad65971c53424aaeb21f009454414c
series3 = frame["d"]
frame
series3
frame.sub(series3, axis="index")

In [ ]:
#! ipython id=034aa9e1976846a888eb7f4d16586081
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame
np.abs(frame)

In [ ]:
#! ipython id=33d3e9f69e734a63b4126e27b8a3621a
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

In [ ]:
#! ipython id=4c55244879094bf5811d05244d2a230d
frame.apply(f1, axis="columns")

In [ ]:
#! ipython id=2d02bdcf56984d359a678eda51cfc90a
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

In [ ]:
#! ipython id=03714284e3a74941a7a81c9f8225dad2
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

In [ ]:
#! ipython id=8ff61d5965c44373b2fbd3d6c6d055e1
frame["e"].map(my_format)

In [ ]:
#! ipython id=d0e3fb6710a04be7b65557895820e8ee
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj
obj.sort_index()

In [ ]:
#! ipython id=e6fb8d18326d4d73bb700eb7a5dab7dd
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame
frame.sort_index()
frame.sort_index(axis="columns")

In [ ]:
#! ipython id=7f3bf86fc9dd4cbfa517949a64a71146
frame.sort_index(axis="columns", ascending=False)

In [ ]:
#! ipython id=b0d33ccb4dbc4ec8852f688a921f880b
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

In [ ]:
#! ipython id=427d6873c73b4c738385e2121309c51b
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

In [ ]:
#! ipython id=e1a336ca986046c8b0aa1eeb8177f7c0
obj.sort_values(na_position="first")

In [ ]:
#! ipython id=d18ce999bf1d435381d8049084ad1572
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame
frame.sort_values("b")

In [ ]:
#! ipython id=e8d81f94d83d41c6a58ae00f2e4b7479
frame.sort_values(["a", "b"])

In [ ]:
#! ipython id=848608e226a74f93919a4e2142671521
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

In [ ]:
#! ipython id=b1493f954289435bbb9407bf167522f8
obj.rank(method="first")

In [ ]:
#! ipython id=9c90dab0cadc4eaebcf98eba4989d952
obj.rank(ascending=False)

In [ ]:
#! ipython id=16017d1637de4b5ba9c49a268b6bee22
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
frame
frame.rank(axis="columns")

In [ ]:
#! ipython id=72b1b246fbfa43dbaf69cf8cf27c0955
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

In [ ]:
#! ipython id=de8dc594c6aa49f78d50be960f071703
obj.index.is_unique

In [ ]:
#! ipython id=c46c8ff26d6748f4b58fc9f011016596
obj["a"]
obj["c"]

In [ ]:
#! ipython id=d88c0cebdc6c415f9189e69148daa4b1
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a", "b", "b", "c"])
df
df.loc["b"]
df.loc["c"]

In [ ]:
#! ipython id=be356bb6c69b42a8b08bb64a882be75a
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"],
                  columns=["one", "two"])
df

In [ ]:
#! ipython id=9667d27e90654379827c6ec2f4279767
df.sum()

In [ ]:
#! ipython id=9c79fbba54b94ff1b8221179c035326b
df.sum(axis="columns")

In [ ]:
#! ipython id=39cfbf6aadb94a95b34e474d1c0ac79c
df.sum(axis="index", skipna=False)
df.sum(axis="columns", skipna=False)

In [ ]:
#! ipython id=D35C0B9048F14176B6E5D0D8E5C77AC7
df.mean(axis="columns")

In [ ]:
#! ipython id=0e594ab9fbac4f03a872ce850303250c
df.idxmax()

In [ ]:
#! ipython id=a496b59741e14566aa71f41813e209d4
df.cumsum()

In [ ]:
#! ipython id=05b39485471d4aebb3ddc860d8278662
df.describe()

In [ ]:
#! ipython id=65e9049764c74b3dbea8926c6943f0cf
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()

In [ ]:
#! ipython id=e97bd8c699eb46259b5bc4d9a50b918b
price = pd.read_pickle("przykłady/yahoo_ceny.pkl")
volume = pd.read_pickle("przykłady/yahoo_liczby.pkl")

In [ ]:
#! ipython id=199d47b63f174740850946cb9d8c09bd
returns = price.pct_change()
returns.tail()

In [ ]:
#! ipython id=acc082d6d7764e0ebfedaf4a92aa5773
returns["MSFT"].corr(returns["IBM"])
returns["MSFT"].cov(returns["IBM"])

In [ ]:
#! ipython id=816399a611f64102ade1a2922528a35c
returns["MSFT"].corr(returns["IBM"])

In [ ]:
#! ipython id=631a9370002647c4ba7ffbf73e239c5f
returns.corr()
returns.cov()

In [ ]:
#! ipython id=668730d660dd4811aff520a5e870b532
returns.corrwith(returns["IBM"])

In [ ]:
#! ipython id=07109c0f2f1a442f80c3cd9212519342
returns.corrwith(volume)

In [ ]:
#! ipython id=90d33c8d9c4543029cad491971f29316
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [ ]:
#! ipython id=18c2f28cf84c4223bb3a96445e2c53e4
uniques = obj.unique()
uniques

In [ ]:
#! ipython id=fb21f3506cb848c1a81c78348cb25847
obj.value_counts()

In [ ]:
#! ipython id=fcb65a23a9b749048c6c1d292392c8c5
pd.value_counts(obj.to_numpy(), sort=False)

In [ ]:
#! ipython id=045ee2714cf3417b98224a725cb9af71
obj
mask = obj.isin(["b", "c"])
mask
obj[mask]

In [ ]:
#! ipython id=e2794101c4db4b8aae1a9d50f0e3b200
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

In [ ]:
#! ipython id=43b21608636349b881aadf2a75987ec7
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
data

In [ ]:
#! ipython id=9ba487d2333f4a509874619fa6ee6026
data["Qu1"].value_counts().sort_index()

In [ ]:
#! ipython id=0e370e3e65534ed7938ffe5e7d19bb58
result = data.apply(pd.value_counts).fillna(0)
result

In [ ]:
#! ipython id=2AF29992875D411F801CAC28587E96D9
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data
data.value_counts()

In [ ]:
#! ipython suppress id=1ab79407b26d4ee9b72f448cb4ea2fe1
%popd

In [ ]:
#! ipython suppress id=ed35ffdee5f94d9c88d2a466c0526684
pd.options.display.max_rows = PREVIOUS_MAX_ROWS